
package dkvz.UI;

import dkvz.model.*;

/**
 *
 * @author william
 */
public class JFrameItem extends javax.swing.JFrame {

    private JFrameMain mainFrame = null;
    private Item itemToModify = null;
    
    /**
     * Creates new form JFrameItem
     */
    public JFrameItem(JFrameMain mainFrame) {
        this.mainFrame = mainFrame;
        this.itemToModify = null;
        this.jTextFieldItemID.setEditable(true);
        this.jTextFieldItemID.setEnabled(true);
        initComponents();
    }
    
    public JFrameItem(JFrameMain mainFrame, Item itemToModify) {
        this.mainFrame = mainFrame;
        this.itemToModify = itemToModify;
        this.jTextFieldItemID.setText(Long.toString(itemToModify.getId()));
        this.jTextFieldItemID.setEditable(false);
        this.jTextFieldItemID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jLabelItemID = new javax.swing.JLabel();
        jTextFieldItemID = new javax.swing.JTextField();
        jPanelCenter = new javax.swing.JPanel();
        jLabelCraftID = new javax.swing.JLabel();
        jLabelCraftQty = new javax.swing.JLabel();
        jTextFieldCraftID = new javax.swing.JTextField();
        jSpinnerCraftQty = new javax.swing.JSpinner();
        jButtonCraftAdd = new javax.swing.JButton();
        jButtonCraftRemove = new javax.swing.JButton();
        jComboBoxCraftItems = new javax.swing.JComboBox();
        jPanelBottom = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTop.setBorder(javax.swing.BorderFactory.createTitledBorder("Add item to list"));

        jLabelItemID.setText("Item ID:");
        jPanelTop.add(jLabelItemID);

        jTextFieldItemID.setColumns(12);
        jPanelTop.add(jTextFieldItemID);

        getContentPane().add(jPanelTop, java.awt.BorderLayout.NORTH);

        jPanelCenter.setBorder(javax.swing.BorderFactory.createTitledBorder("Components required to craft item"));

        jLabelCraftID.setText("Item ID");

        jLabelCraftQty.setText("Quantity");

        jButtonCraftAdd.setText("Add/Edit");

        jButtonCraftRemove.setText("Remove");
        jButtonCraftRemove.setEnabled(false);

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxCraftItems, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCraftID, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jTextFieldCraftID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCenterLayout.createSequentialGroup()
                                .addComponent(jLabelCraftQty)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSpinnerCraftQty, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCraftAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCraftRemove)))
                .addContainerGap())
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCraftID)
                    .addComponent(jLabelCraftQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCraftID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCraftQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCraftAdd)
                    .addComponent(jButtonCraftRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCraftItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanelBottom.add(jButtonOK);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanelBottom.add(jButtonClose);

        getContentPane().add(jPanelBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @return the mainFrame
     */
    public JFrameMain getMainFrame() {
        return mainFrame;
    }

    /**
     * @param mainFrame the mainFrame to set
     */
    public void setMainFrame(JFrameMain mainFrame) {
        this.mainFrame = mainFrame;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCraftAdd;
    private javax.swing.JButton jButtonCraftRemove;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxCraftItems;
    private javax.swing.JLabel jLabelCraftID;
    private javax.swing.JLabel jLabelCraftQty;
    private javax.swing.JLabel jLabelItemID;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JSpinner jSpinnerCraftQty;
    private javax.swing.JTextField jTextFieldCraftID;
    private javax.swing.JTextField jTextFieldItemID;
    // End of variables declaration//GEN-END:variables
}
