
package dkvz.UI;

import dkvz.model.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Alain
 */
public class JFrameTransactionLogging extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTransactionLogging
     */
    public JFrameTransactionLogging() {
        initComponents();
    }
    
    public void logMessage(String message) {
        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
	String dateToStr = format.format(new Date());
        this.jTextAreaLog.append(dateToStr.concat(" - ").concat(message).concat("\r\n"));
        this.jTextAreaLog.setCaretPosition(this.jTextAreaLog.getText().length());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jComboBoxTransactionFile = new javax.swing.JComboBox();
        jButtonStartStopLogging = new javax.swing.JButton();
        jButtonStopAllLogging = new javax.swing.JButton();
        jButtonDeleteLog = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jSplitPaneCenter = new javax.swing.JSplitPane();
        jScrollPanelLog = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTableTransactionLog = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaction Logging");

        jPanelTop.setLayout(new javax.swing.BoxLayout(jPanelTop, javax.swing.BoxLayout.X_AXIS));

        jComboBoxTransactionFile.setModel(new DefaultComboBoxModel<Item>());
        jPanelTop.add(jComboBoxTransactionFile);

        jButtonStartStopLogging.setText("Start Logging");
        jPanelTop.add(jButtonStartStopLogging);

        jButtonStopAllLogging.setText("Stop All Logging");
        jPanelTop.add(jButtonStopAllLogging);

        jButtonDeleteLog.setText("Delete Log");
        jPanelTop.add(jButtonDeleteLog);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanelTop.add(jButtonClose);

        getContentPane().add(jPanelTop, java.awt.BorderLayout.NORTH);

        jSplitPaneCenter.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPaneCenter.setResizeWeight(1.0);

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPanelLog.setViewportView(jTextAreaLog);

        jSplitPaneCenter.setBottomComponent(jScrollPanelLog);

        jTableTransactionLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTable.setViewportView(jTableTransactionLog);

        jSplitPaneCenter.setTopComponent(jScrollPaneTable);

        getContentPane().add(jSplitPaneCenter, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(775, 622));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDeleteLog;
    private javax.swing.JButton jButtonStartStopLogging;
    private javax.swing.JButton jButtonStopAllLogging;
    private javax.swing.JComboBox jComboBoxTransactionFile;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JScrollPane jScrollPanelLog;
    private javax.swing.JSplitPane jSplitPaneCenter;
    private javax.swing.JTable jTableTransactionLog;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables
}
